# GitHub Secret Scanning Allowlist
# This file tells GitHub that the Firebase API key in firebase-config.js is intentionally public
# Firebase web API keys are designed to be public - security is enforced by Firestore rules

paths-allowlist:
  - firebase-config.js
